export interface BiologicalSolution {
  id: string;
  organism: string;
  scientificName: string;
  category: string;
  challenge: string;
  mechanism: string;
  advantage: string;
  implementation: string;
  image: string;
  tags: string[];
  relevanceScore?: number;
  metrics: {
    efficiency: number;
    sustainability: number;
    manufacturability: number;
  };
  designVariants: Array<{
    name: string;
    description: string;
    specs: string[];
  }>;
  researchPapers?: string[];
  realWorldApplications?: string[];
}

export const problemExamples = [
  { title: "Passive Building Cooling", description: "Design a building that maintains comfortable temperature without air conditioning", icon: "❄️" },
  { title: "Ultra-Strong Reusable Adhesive", description: "Create an adhesive that works wet or dry, is reusable, and non-toxic", icon: "🧴" },
  { title: "Efficient Wind Turbine Blades", description: "Design wind turbine blades that maximize energy capture with minimal noise", icon: "💨" },
  { title: "Self-Cleaning Waterproof Surface", description: "Create a material that repels water and dirt without chemical coatings", icon: "💧" },
  { title: "Lightweight Strong Structures", description: "Build structures that are strong yet ultra-lightweight like bones and honeycombs", icon: "⚙️" },
  { title: "Efficient Swimming Propulsion", description: "Design hulls and propellers for underwater vessels with minimal drag", icon: "🏊" },
  { title: "Silent Flight Systems", description: "Create aerodynamic designs with minimal noise generation", icon: "🦉" },
  { title: "Energy Harvesting", description: "Capture and store energy efficiently from environment like organisms do", icon: "⚡" },
];

// Base organisms with detailed information
const baseOrganisms = [
  // COOLING & VENTILATION
  {
    organism: "African Termite Mound",
    scientificName: "Macrotermes michaelseni",
    category: "Cooling & Ventilation",
    challenge: "Passive Building Cooling",
    mechanism: "Termites create vertical and horizontal passages using air density differences",
    advantage: "90% energy reduction; passive cooling without electricity",
    implementation: "Design building ventilation with helical channels and diagonal vents",
    image: "🏛️",
    tags: ["cooling", "ventilation", "passive", "architecture"],
    variants: ["Spiral Ventilation Core", "Multi-Stack System", "Moisture-Responsive Dampers"],
  },
  {
    organism: "Emperor Penguin Huddle",
    scientificName: "Aptenodytes forsteri",
    category: "Cooling & Ventilation",
    challenge: "Efficient Group Thermal Management",
    mechanism: "Penguins rotate positions in huddles, distributing warmth through group dynamics",
    advantage: "80% energy savings in heating; self-organizing thermal management",
    implementation: "Design modular heating systems with rotating zones",
    image: "🐧",
    tags: ["thermal", "group", "rotation", "efficiency"],
    variants: ["Rotational Heat Zone", "Dynamic Insulation", "Biomimetic Crowd Flow"],
  },
  {
    organism: "Namibian Desert Beetle",
    scientificName: "Stenocara gracilipes",
    category: "Cooling & Ventilation",
    challenge: "Water Harvesting & Cooling",
    mechanism: "Beetle carapace has hydrophilic peaks and hydrophobic valleys for water capture",
    advantage: "Harvests water from 10% humidity; passive cooling effect",
    implementation: "Create textured surfaces with alternating wettability patterns",
    image: "🪲",
    tags: ["water-harvesting", "cooling", "passive", "sustainable"],
    variants: ["Wettability-Patterned Coating", "3D Textured Collector", "Smart Surface Membrane"],
  },
  {
    organism: "Eucalyptus Trees",
    scientificName: "Eucalyptus species",
    category: "Cooling & Ventilation",
    challenge: "Thermal Buffering",
    mechanism: "Eucalyptus leaves emit heat at night through radiation efficiently",
    advantage: "Night-time cooling without energy; faster thermal response",
    implementation: "Design surfaces with high emissivity coatings and thin walls",
    image: "🌳",
    tags: ["cooling", "thermal", "passive", "nocturnal"],
    variants: ["High-Emissivity Coating", "Thin-Wall Heat Sink", "Bifunctional Surface"],
  },
  {
    organism: "Evaporative Cooling Frog",
    scientificName: "Litoria caerulea",
    category: "Cooling & Ventilation",
    challenge: "Evaporative Cooling System",
    mechanism: "Frogs use skin evaporation with specialized mucus production for cooling",
    advantage: "Efficient evaporative cooling in humid conditions",
    implementation: "Create porous materials with moisture-wicking capabilities",
    image: "🐸",
    tags: ["evaporative", "cooling", "moisture", "efficiency"],
    variants: ["Porous Cooling Membrane", "Mucus-Inspired Coating", "Hydrogel System"],
  },
  // ADHESIVES & FASTENING
  {
    organism: "Gecko Feet",
    scientificName: "Hemidactylus frenatus",
    category: "Adhesives & Fastening",
    challenge: "Ultra-Strong Reusable Adhesive",
    mechanism: "Gecko toes have 2M micro-hairs using van der Waals forces for reversible adhesion",
    advantage: "Reusable unlimited times; works on any surface; no residue",
    implementation: "Create synthetic polymers with hierarchical micro/nano-scale bristles",
    image: "🦎",
    tags: ["adhesive", "fastening", "reversible", "biomimetic"],
    variants: ["Polymeric Setae Film", "3D-Printed Hierarchical", "Hybrid Bio-Polymer"],
  },
  {
    organism: "Blue Mussel",
    scientificName: "Mytilus edulis",
    category: "Adhesives & Fastening",
    challenge: "Underwater Adhesive",
    mechanism: "Mussels produce byssal threads with DOPA proteins that cross-link in water",
    advantage: "Works underwater; 25 MPa strength; biodegradable",
    implementation: "Engineer proteins or polymers with catechol groups",
    image: "🐚",
    tags: ["adhesive", "underwater", "biodegradable", "marine"],
    variants: ["Recombinant Mussel Protein", "Catechol-Based Polymer", "Byssal Thread Fiber"],
  },
  {
    organism: "Tree Frog Toe Pads",
    scientificName: "Phyllomedusa species",
    category: "Adhesives & Fastening",
    challenge: "Wet Surface Grip",
    mechanism: "Frog toe pads secrete mucus with micro-ridges for wet adhesion",
    advantage: "Grips wet surfaces better than dry; self-lubricating",
    implementation: "Create micropatterned surfaces with liquid-secreting capabilities",
    image: "🐸",
    tags: ["adhesive", "wet", "friction", "dynamic"],
    variants: ["Liquid-Secreting Pad", "Hybrid Wettability Pattern", "Pressure-Sensitive Pad"],
  },
  {
    organism: "Acorn Barnacle",
    scientificName: "Semibalanus balanoides",
    category: "Adhesives & Fastening",
    challenge: "Ultra-Durable Ocean Adhesive",
    mechanism: "Barnacles produce proteinaceous cement that hardens underwater",
    advantage: "Extremely durable in marine conditions; permanent adhesion",
    implementation: "Engineer proteins with cross-linking chemistry for marine environments",
    image: "🦪",
    tags: ["adhesive", "marine", "durable", "permanent"],
    variants: ["Bioengineered Cement", "Two-Part Marine Epoxy", "Cement Coating"],
  },
  {
    organism: "Spider Dragline",
    scientificName: "Araneus diadematus",
    category: "Adhesives & Fastening",
    challenge: "High-Strength Elastic Line",
    mechanism: "Spider dragline combines high tensile strength with elasticity",
    advantage: "Lighter than steel; elastic recovery; biodegradable",
    implementation: "Synthesize and spin recombinant spider silk",
    image: "🕸️",
    tags: ["fiber", "elastic", "strength", "biodegradable"],
    variants: ["Synthetic Spider Silk", "Multi-Ply Dragline Cable", "Hybrid Silk-Polymer"],
  },
  // AERODYNAMICS & HYDRODYNAMICS
  {
    organism: "Humpback Whale Fins",
    scientificName: "Megaptera novaeangliae",
    category: "Aerodynamics & Hydrodynamics",
    challenge: "Efficient Wind Turbine Blades",
    mechanism: "Tubercles on whale fins create beneficial vortices to increase lift",
    advantage: "20-40% aerodynamic improvement; 30% noise reduction",
    implementation: "Add tubercle-like bumps to turbine blade leading edges",
    image: "🐋",
    tags: ["aerodynamics", "efficiency", "turbines", "hydrodynamics"],
    variants: ["Leading Edge Tubercles", "Full-Surface Wave Pattern", "Adaptive Tubercle System"],
  },
  {
    organism: "Herring Gull Wing",
    scientificName: "Larus argentatus",
    category: "Aerodynamics & Hydrodynamics",
    challenge: "Energy-Efficient Gliding",
    mechanism: "Gull wings have slotted primary feathers reducing induced drag",
    advantage: "30% energy reduction during flight; 2-3x glide distance",
    implementation: "Design aircraft blades with slotted wingtips",
    image: "🦅",
    tags: ["aerodynamics", "efficiency", "gliding", "vortex"],
    variants: ["Slotted Winglet Extension", "Feathered Wingtip Design", "Divergent Trailing Edge"],
  },
  {
    organism: "Shark Skin",
    scientificName: "Lamna nasus",
    category: "Aerodynamics & Hydrodynamics",
    challenge: "Hydrodynamic Drag Reduction",
    mechanism: "Shark skin has microscopic riblets aligning turbulent flow",
    advantage: "5-10% drag reduction; passive; self-maintaining",
    implementation: "Create microscopic parallel groove patterns on surfaces",
    image: "🦈",
    tags: ["hydrodynamics", "drag-reduction", "passive", "friction"],
    variants: ["Riblet Film Coating", "Molded Riblet Surface", "3D-Printed Riblet"],
  },
  {
    organism: "Dolphin Melon Organ",
    scientificName: "Tursiops truncatus",
    category: "Aerodynamics & Hydrodynamics",
    challenge: "Underwater Sonar & Navigation",
    mechanism: "Dolphin melon focuses sound waves with high precision",
    advantage: "Detailed 3D perception at distance; works in murky water",
    implementation: "Engineer acoustic lens systems using gradient-index materials",
    image: "🐬",
    tags: ["sonar", "acoustics", "navigation", "sensing"],
    variants: ["Acoustic Lens Material", "Phased Array Transducer", "Passive Resonator"],
  },
  {
    organism: "Sailfish Sail",
    scientificName: "Istiophorus platypterus",
    category: "Aerodynamics & Hydrodynamics",
    challenge: "Fluid Flow Optimization",
    mechanism: "Sailfish dorsal fin creates complex vortex patterns for maneuverability",
    advantage: "Superior agility and turning radius in water",
    implementation: "Design fins with optimized curvature and spacing",
    image: "🐟",
    tags: ["hydrodynamics", "maneuverability", "fin", "optimization"],
    variants: ["Curved Fin Design", "Vortex-Generating Pattern", "Dynamic Sail Shape"],
  },
  // SURFACE PROPERTIES
  {
    organism: "Lotus Leaf",
    scientificName: "Nelumbo nucifera",
    category: "Surface Properties",
    challenge: "Self-Cleaning Waterproof Surface",
    mechanism: "Lotus has microscopic bumps with wax creating superhydrophobic surface",
    advantage: "Self-cleaning without chemicals; 95% fouling reduction",
    implementation: "Create micro-textured surface with hydrophobic nanoparticles",
    image: "🌸",
    tags: ["self-cleaning", "hydrophobic", "surface", "coating"],
    variants: ["Nanoparticle Coating", "Textured Polymer Film", "Bio-Inspired Wax Layer"],
  },
  {
    organism: "Rose Petal",
    scientificName: "Rosa species",
    category: "Surface Properties",
    challenge: "Adhesive Yet Repellent Surface",
    mechanism: "Rose petals have hierarchical structures combining water attraction and repulsion",
    advantage: "Holds water while repelling dirt; maintains color",
    implementation: "Create hierarchical surface with dual-scale features",
    image: "🌹",
    tags: ["hydrophobic", "adhesion", "surface", "dual-scale"],
    variants: ["Dual-Scale Hierarchical", "Petal-Inspired Coating", "3D-Printed Texture"],
  },
  {
    organism: "Fish Scale",
    scientificName: "Oreochromis niloticus",
    category: "Surface Properties",
    challenge: "Lightweight Protective Armor",
    mechanism: "Fish scales have overlapping layered structure with flexible joints",
    advantage: "80% lighter than rigid armor; self-healing capability",
    implementation: "Design layered composite with overlapping elements",
    image: "🐟",
    tags: ["protection", "lightweight", "flexible", "composite"],
    variants: ["Overlapping Plate Armor", "Layered Composite Shield", "Segmented Structure"],
  },
  {
    organism: "Nacre (Mother-of-Pearl)",
    scientificName: "Pinctada species",
    category: "Surface Properties",
    challenge: "Iridescent Protective Coating",
    mechanism: "Nacre uses aragonite platelets with specific thickness for light interference",
    advantage: "Beautiful colors without dyes; 2-3 GPa hardness",
    implementation: "Create layered structures with specific aragonite crystal size",
    image: "✨",
    tags: ["iridescent", "coating", "protective", "optical"],
    variants: ["Nacre-Inspired Coating", "Synthetic Pearl Composite", "Structural Color Filter"],
  },
  {
    organism: "Bombyx Mori (Silkworm)",
    scientificName: "Bombyx mori",
    category: "Surface Properties",
    challenge: "Smooth Low-Friction Surface",
    mechanism: "Silk fibers have smooth crystalline structure minimizing friction",
    advantage: "Ultra-low friction; smooth to touch; biodegradable",
    implementation: "Engineer smooth polymers mimicking silk crystallinity",
    image: "🦗",
    tags: ["friction", "smooth", "silk", "low-resistance"],
    variants: ["Silk-Like Polymer", "Crystalline Coating", "Bio-Inspired Fiber"],
  },
  // MATERIALS & STRUCTURES (expanding significantly)
  {
    organism: "Spider Web Silk",
    scientificName: "Nephila edulis",
    category: "Materials & Structures",
    challenge: "Ultra-Strong Lightweight Material",
    mechanism: "Spider silk is 5x stronger than steel by weight with elasticity",
    advantage: "5x stronger than steel; 35% elastic; biodegradable",
    implementation: "Synthesize recombinant spider silk proteins",
    image: "🕷️",
    tags: ["materials", "strength", "lightweight", "biopolymer"],
    variants: ["Recombinant Silk Fiber", "Hybrid Silk-Polymer", "Silk-Inspired Nanofiber"],
  },
  {
    organism: "Abalone Shell",
    scientificName: "Haliotis species",
    category: "Materials & Structures",
    challenge: "Impact-Resistant Strong Composite",
    mechanism: "Abalone shell has layers of calcium carbonate with organic matrix",
    advantage: "3000x tougher than raw material; combines hardness with toughness",
    implementation: "Create layered composites with ceramic tiles in polymer matrix",
    image: "🐚",
    tags: ["composite", "impact-resistant", "structure", "biomimetic"],
    variants: ["Ceramic-Polymer Laminate", "3D Printed Nacre-Like", "Bio-Inspired Adhesive Layering"],
  },
  {
    organism: "Mammalian Bone",
    scientificName: "Homo sapiens",
    category: "Materials & Structures",
    challenge: "Strong Yet Lightweight Structure",
    mechanism: "Bone combines hard mineral with soft protein in hierarchical structure",
    advantage: "25x stronger than steel by weight; self-healing; adaptable",
    implementation: "Design composite structures with solid cortical shell and porous interior",
    image: "💀",
    tags: ["composite", "structure", "lightweight", "adaptive"],
    variants: ["Cortical-Trabecular Composite", "Gradient Density Structure", "3D-Printed Bio-Composite"],
  },
  {
    organism: "Honeycomb (Bee Hive)",
    scientificName: "Apis mellifera",
    category: "Materials & Structures",
    challenge: "Lightweight Yet Strong Structure",
    mechanism: "Hexagonal honeycomb provides maximum volume with minimum material",
    advantage: "99% volume efficiency; high strength-to-weight; self-supporting",
    implementation: "Design structures using hexagonal cell geometry",
    image: "🍯",
    tags: ["structure", "efficiency", "lightweight", "geometry"],
    variants: ["Hexagonal Cell Panel", "Gradient Cell Honeycomb", "Bio-Foam Honeycomb"],
  },
  {
    organism: "Pomelo Peel",
    scientificName: "Citrus maxima",
    category: "Materials & Structures",
    challenge: "Impact Protection Without Rigidity",
    mechanism: "Pomelo peel has spongy cellular structure absorbing energy through deformation",
    advantage: "Energy absorption without damage; lightweight; biodegradable",
    implementation: "Design foam or cellular structures with tuned porosity",
    image: "🍊",
    tags: ["protection", "absorption", "cellular", "impact"],
    variants: ["Cellular Foam Packing", "Gradient Cell Protection", "Bio-Inspired Packing Material"],
  },
  {
    organism: "Bamboo Plant",
    scientificName: "Bambusa species",
    category: "Materials & Structures",
    challenge: "Renewable Strong Lightweight Material",
    mechanism: "Bamboo has fiber structure with optimal radial and tangential arrangement",
    advantage: "Faster renewal than timber; high strength; sustainable",
    implementation: "Develop optimized bamboo composites and laminates",
    image: "🎋",
    tags: ["renewable", "strong", "lightweight", "sustainable"],
    variants: ["Bamboo Laminate", "Fiber-Aligned Composite", "Bio-Engineered Bamboo"],
  },
];

// Function to generate massive diverse solutions
function generateSolutions(): BiologicalSolution[] {
  const solutions: BiologicalSolution[] = [];
  let idCounter = 0;

  // Add all base organisms directly (no duplicates)
  baseOrganisms.forEach((org) => {
    solutions.push({
      id: `bio-${idCounter++}`,
      organism: org.organism,
      scientificName: org.scientificName,
      category: org.category,
      challenge: org.challenge,
      mechanism: org.mechanism,
      advantage: org.advantage,
      implementation: org.implementation,
      image: org.image,
      tags: org.tags,
      metrics: {
        efficiency: 0.7 + Math.random() * 0.28,
        sustainability: 0.75 + Math.random() * 0.24,
        manufacturability: 0.6 + Math.random() * 0.38,
      },
      designVariants: org.variants.map((v) => ({
        name: v,
        description: `${v} variant for ${org.challenge}`,
        specs: [
          `Performance: ${80 + Math.floor(Math.random() * 20)}%`,
          `Cost index: ${Math.floor(100 + Math.random() * 150)}`,
          `Scalability: ${["High", "Medium", "Variable"][Math.floor(Math.random() * 3)]}`,
        ],
      })),
    });
  });

  // Add truly diverse additional organisms (26 more base organisms)
  const diverseOrganisms = [
    {
      organism: "Dragonfly Wing",
      scientificName: "Anisoptera species",
      category: "Aerodynamics & Hydrodynamics",
      challenge: "Ultra-Fast Lightweight Aircraft Design",
      mechanism: "Dragonfly wings have dual-wing system with independent movement",
      advantage: "Ultra-fast maneuverability; minimal energy per distance",
      implementation: "Design quad-wing aircraft with independent actuators",
    },
    {
      organism: "Peacock Feather",
      scientificName: "Pavo cristatus",
      category: "Optics & Colors",
      challenge: "Dynamic Structural Color Display",
      mechanism: "Peacock feathers use multilayer interference for iridescent colors",
      advantage: "Color changes with viewing angle; no pigments needed",
      implementation: "Create angle-dependent photonic structures",
    },
    {
      organism: "Firefly Lantern",
      scientificName: "Photinus pyralis",
      category: "Energy Harvesting",
      challenge: "Ultra-Efficient Biological Light Production",
      mechanism: "Firefly abdomen produces light with 95% quantum efficiency",
      advantage: "Nearly all energy converts to light; no heat loss",
      implementation: "Engineer bioluminescent proteins and optical guides",
    },
    {
      organism: "Cat Eye Tapetum",
      scientificName: "Felis catus",
      category: "Optics & Colors",
      challenge: "Low-Light Vision Enhancement",
      mechanism: "Cat eyes have reflective layer (tapetum lucidum) doubling light capture",
      advantage: "See in 6x lower light than humans; passive enhancement",
      implementation: "Design reflective coatings for optical sensors",
    },
    {
      organism: "Pit Viper Heat Sensor",
      scientificName: "Crotalus species",
      category: "Sensing & Detection",
      challenge: "Infrared Temperature Detection",
      mechanism: "Pit viper has sensitive pits detecting <0.03°C temperature difference",
      advantage: "Detects prey in complete darkness; passive sensing",
      implementation: "Create microbolometer arrays in reflector geometry",
    },
    {
      organism: "Dog Olfactory System",
      scientificName: "Canis lupus familiaris",
      category: "Sensing & Detection",
      challenge: "Ultra-Sensitive Chemical Detection",
      mechanism: "Dogs smell parts-per-trillion using 300M olfactory receptors",
      advantage: "Detect individual molecules; complex mixture analysis",
      implementation: "Design chemical sensor arrays with pattern recognition",
    },
    {
      organism: "Spider Vibration Sensing",
      scientificName: "Araneae species",
      category: "Sensing & Detection",
      challenge: "Distributed Vibration Monitoring",
      mechanism: "Spiders detect vibrations through web using lyriform organs",
      advantage: "Ultra-sensitive distributed network; multiplexed information",
      implementation: "Create vibration sensor networks using accelerometers",
    },
    {
      organism: "Cactus Water Storage",
      scientificName: "Cactaceae family",
      category: "Water Management",
      challenge: "Efficient Water Capture & Storage",
      mechanism: "Cactus captures sparse rainfall with wide roots; stores with minimal loss",
      advantage: "2-3x more water capture; stores for months; sustainable",
      implementation: "Design high-surface collectors with low-evaporation storage",
    },
    {
      organism: "Mangrove Salt Filtration",
      scientificName: "Rhizophora species",
      category: "Water Management",
      challenge: "Seawater Desalination",
      mechanism: "Mangrove roots filter 90% salt from seawater osmotically",
      advantage: "Passive salt removal; freshwater recovery; sustainable",
      implementation: "Engineer selective membrane systems using osmotic pressure",
    },
    {
      organism: "Dung Beetle Moisture Harvesting",
      scientificName: "Scarabaeus species",
      category: "Water Management",
      challenge: "Atmospheric Water Harvesting",
      mechanism: "Beetle exoskeleton captures moisture through mixed-wettability",
      advantage: "Harvests from 50% humidity air; passive; integrated",
      implementation: "Create textured surfaces with alternating wettability",
    },
    {
      organism: "Dinoflagellate Bioluminescence",
      scientificName: "Dinophysis species",
      category: "Communication & Signaling",
      challenge: "Underwater Optical Communication",
      mechanism: "Dinoflagellates emit light via chemiluminescence (near 100% efficiency)",
      advantage: "High efficiency light; underwater communication; chemical energy",
      implementation: "Design chemiluminescent reaction systems with optical guides",
    },
    {
      organism: "Humpback Whale Song",
      scientificName: "Megaptera novaeangliae",
      category: "Communication & Signaling",
      challenge: "Long-Distance Underwater Communication",
      mechanism: "Whale songs travel 100+ km underwater using low frequencies",
      advantage: "Long-range communication; penetrates water; complex information",
      implementation: "Design low-frequency acoustic transmitters with strategic frequency selection",
    },
    {
      organism: "Plant Leaf Photosynthesis",
      scientificName: "Various species",
      category: "Energy Harvesting",
      challenge: "Direct Solar Energy to Chemical Conversion",
      mechanism: "Leaves convert light to chemical energy with organized pigments",
      advantage: "Direct solar energy capture; ambient temperature; produces useful products",
      implementation: "Design photovoltaic systems or artificial photosynthesis",
    },
    {
      organism: "Electric Eel",
      scientificName: "Electrophorus electricus",
      category: "Energy Harvesting",
      challenge: "Biological Electrical Power Generation",
      mechanism: "Eel generates 860V through stacked electroplaques (ion pumping)",
      advantage: "Biological power; no moving parts; controllable output",
      implementation: "Design stacked ion-pumping cells creating bioelectric potential",
    },
    {
      organism: "Gecko Climbing",
      scientificName: "Hemidactylus frenatus",
      category: "Movement & Locomotion",
      challenge: "Wall Climbing Without Adhesive",
      mechanism: "Gecko climbs vertical/inverted using van der Waals forces on hairy feet",
      advantage: "Climbs any surface; reversible adhesion; high speed",
      implementation: "Create hairy climbing pads with optimal micro-structure",
    },
    {
      organism: "Jellyfish Propulsion",
      scientificName: "Aurelia aurita",
      category: "Movement & Locomotion",
      challenge: "Efficient Fluid Propulsion",
      mechanism: "Jellyfish propel via pulsed jet using elastic bell contraction",
      advantage: "10x more efficient than fish; works in density-stratified fluids",
      implementation: "Design pulsed jet thrusters with elastic bell structures",
    },
    {
      organism: "Springtail Jumping",
      scientificName: "Collembola species",
      category: "Movement & Locomotion",
      challenge: "High-Performance Jumping",
      mechanism: "Springtail uses spring-loaded furcula for extreme acceleration",
      advantage: "10-100x body length jumps; minimal prep time; repeatable",
      implementation: "Design elastic latching mechanisms for stored energy release",
    },
    {
      organism: "Tree Growth Pattern",
      scientificName: "Quercus species",
      category: "Growth & Development",
      challenge: "Self-Optimizing Structure Growth",
      mechanism: "Trees grow by optimizing structure based on wind loads and light",
      advantage: "Self-optimizing; minimal material; inherent strength; adaptive",
      implementation: "Design computational growth models for stress-aware structures",
    },
    {
      organism: "Nautilus Shell Spiral",
      scientificName: "Nautilus pompilius",
      category: "Growth & Development",
      challenge: "Logarithmic Growth Scaling",
      mechanism: "Nautilus creates progressively larger chambers following golden ratio",
      advantage: "Optimal scaling; structural efficiency; minimal material per volume",
      implementation: "Design systems following golden ratio/Fibonacci sequences",
    },
    {
      organism: "Starfish Regeneration",
      scientificName: "Asteroidea species",
      category: "Self-Repair & Healing",
      challenge: "Biological Self-Repair",
      mechanism: "Starfish regrows lost limbs and organs through dedifferentiation",
      advantage: "Complete regeneration; multiple parts replaceable; lifetime renewal",
      implementation: "Engineer self-healing polymers or biological scaffolds",
    },
    {
      organism: "Crocodile Tooth Replacement",
      scientificName: "Crocodylus niloticus",
      category: "Self-Repair & Healing",
      challenge: "Continuous Component Replacement",
      mechanism: "Crocodile continuously replaces teeth using multiple dental laminae",
      advantage: "Lifetime tooth replacement; no decay failures; maintenance-free",
      implementation: "Design distributed manufacturing for continuous component production",
    },
    {
      organism: "Polar Bear Fur",
      scientificName: "Ursus maritimus",
      category: "Thermal Management",
      challenge: "Extreme Cold Insulation",
      mechanism: "Bear fur has hollow transparent hairs trapping air; dense underfur",
      advantage: "Extreme insulation at minimal weight; UV protection",
      implementation: "Design multi-scale insulation with hollow structures",
    },
    {
      organism: "Camel Heat Dissipation",
      scientificName: "Camelus dromedarius",
      category: "Thermal Management",
      challenge: "Desert Heat Dissipation",
      mechanism: "Camel fur is thick with air spaces; light color reflects; minimizes water loss",
      advantage: "2°C cooler in desert heat; minimal water loss; passive",
      implementation: "Design light-colored porous materials for heat dissipation",
    },
    {
      organism: "Desert Iguana Thermoregulation",
      scientificName: "Dipsosaurus dorsalis",
      category: "Thermal Management",
      challenge: "Behavioral Thermal Buffering",
      mechanism: "Iguana adjusts sun exposure and body position for temperature control",
      advantage: "Maintains optimal temperature with minimal energy; behavioral control",
      implementation: "Design smart surfaces with variable thermal properties",
    },
    {
      organism: "Salmon Counter-Current Heat Exchange",
      scientificName: "Salmo salar",
      category: "Thermal Management",
      challenge: "Efficient Heat Recovery",
      mechanism: "Salmon uses blood vessels in gills for counter-current heat exchange",
      advantage: "Prevents heat loss; maintains temperature; passive mechanism",
      implementation: "Design counter-current heat exchangers mimicking gill structure",
    },
    {
      organism: "Woodpecker Shock Absorption",
      scientificName: "Picidae family",
      category: "Materials & Structures",
      challenge: "Impact Shock Absorption",
      mechanism: "Woodpecker skull has spongy bone and cerebrospinal fluid absorbing impacts",
      advantage: "Absorbs 1000+ Gs without injury; repeated high-impact operation",
      implementation: "Create shock-absorbing structures using spongy materials",
    },
  ];

  // Add all diverse organisms (each is a unique base solution)
  diverseOrganisms.forEach((org) => {
    solutions.push({
      id: `bio-${idCounter++}`,
      organism: org.organism,
      scientificName: org.scientificName,
      category: org.category,
      challenge: org.challenge,
      mechanism: org.mechanism,
      advantage: org.advantage,
      implementation: org.implementation,
      image: "🧬",
      tags: [org.category.toLowerCase().replace(/ /g, "-"), org.organism.toLowerCase()],
      metrics: {
        efficiency: 0.65 + Math.random() * 0.33,
        sustainability: 0.70 + Math.random() * 0.29,
        manufacturability: 0.55 + Math.random() * 0.43,
      },
      designVariants: [
        {
          name: "Standard Implementation",
          description: `Basic implementation of ${org.organism} principles`,
          specs: [
            `Efficiency: ${(70 + Math.random() * 25).toFixed(0)}%`,
            `Cost: Medium`,
            `Scalability: High`,
          ],
        },
        {
          name: "Advanced Variant",
          description: `Optimized implementation with enhanced performance`,
          specs: [
            `Efficiency: ${(80 + Math.random() * 18).toFixed(0)}%`,
            `Cost: High`,
            `Scalability: Medium`,
          ],
        },
        {
          name: "Rapid Prototype",
          description: `Quick deployment version for initial testing`,
          specs: [
            `Efficiency: ${(60 + Math.random() * 20).toFixed(0)}%`,
            `Cost: Low`,
            `Scalability: High`,
          ],
        },
      ],
    });
  });

  return solutions;
}

// Generate all solutions on module load
export const organisms = generateSolutions();
