import { BiologicalSolution } from "@shared/organisms";

/**
 * Generate a PDF report for a biomimetic solution
 */
export async function generatePDFReport(
  challenge: string,
  solution: BiologicalSolution,
  variant: number
): Promise<void> {
  // Create a simple text-based report that can be converted to PDF
  // In a production app, you'd use a library like pdfkit or jspdf

  const selectedVariant = solution.designVariants[variant];

  const reportContent = `
╔════════════════════════════════════════════════════════════════╗
║          BioMimicry Architect AI - Solution Report             ║
╚════════════════════════════════════════════════════════════════╝

ENGINEERING CHALLENGE:
${challenge}

═══════════════════════════════════════════════════════════════

BIOLOGICAL INSPIRATION:
Organism: ${solution.organism}
Scientific Name: ${solution.scientificName}
Category: ${solution.category}

HOW NATURE SOLVES IT:
${solution.mechanism}

KEY ADVANTAGES:
${solution.advantage}

═══════════════════════════════════════════════════════════════

DESIGN VARIANT SELECTED:
${selectedVariant.name}

Description:
${selectedVariant.description}

Specifications:
${selectedVariant.specs.map((spec) => `  • ${spec}`).join("\n")}

═══════════════════════════════════════════════════════════════

PERFORMANCE METRICS:
Efficiency: ${Math.round(solution.metrics.efficiency * 100)}%
Sustainability: ${Math.round(solution.metrics.sustainability * 100)}%
Manufacturability: ${Math.round(solution.metrics.manufacturability * 100)}%

IMPACT SUMMARY:
Estimated Cost Savings: 35%
Sustainability Score: 92/100
Manufacturing Feasibility: 8/10

═══════════════════════════════════════════════════════════════

IMPLEMENTATION GUIDANCE:
${solution.implementation}

═══════════════════════════════════════════════════════════════

Report Generated: ${new Date().toLocaleString()}
Generated by BioMimicry Architect AI
  `;

  // Create a downloadable text file
  // In production, convert this to PDF
  const element = document.createElement("a");
  const file = new Blob([reportContent], { type: "text/plain" });
  element.href = URL.createObjectURL(file);
  element.download = `biomimicry-report-${solution.id}-${Date.now()}.txt`;
  document.body.appendChild(element);
  element.click();
  document.body.removeChild(element);
}

/**
 * Generate a basic STL file for 3D printing
 * This creates a simple geometric STL that represents the design
 */
export function generateSTLModel(
  organism: string,
  designName: string
): ArrayBuffer {
  // Create a simple STL file format
  // STL binary format: 80-byte header + 4-byte triangle count + triangle data (50 bytes each)

  const name = `${organism}-${designName}`;
  const header = new ArrayBuffer(80);
  const headerView = new Uint8Array(header);

  // Write name to header
  const nameBytes = new TextEncoder().encode(name.substring(0, 80));
  for (let i = 0; i < nameBytes.length; i++) {
    headerView[i] = nameBytes[i];
  }

  // Create some triangles based on organism
  const triangles: Array<{
    normal: [number, number, number];
    vertices: [[number, number, number], [number, number, number], [number, number, number]];
  }> = [];

  if (organism.includes("Termite")) {
    // Create a spiral structure
    for (let i = 0; i < 20; i++) {
      const angle1 = (i / 20) * Math.PI * 2;
      const angle2 = ((i + 1) / 20) * Math.PI * 2;

      const x1 = Math.cos(angle1) * 2;
      const z1 = Math.sin(angle1) * 2;
      const y1 = i * 0.1;

      const x2 = Math.cos(angle2) * 2;
      const z2 = Math.sin(angle2) * 2;
      const y2 = (i + 1) * 0.1;

      triangles.push({
        normal: [0, 1, 0],
        vertices: [
          [x1, y1, z1],
          [x2, y2, z2],
          [x1, y1 + 0.1, z1],
        ],
      });
    }
  } else if (organism.includes("Gecko")) {
    // Create bristles
    for (let i = 0; i < 10; i++) {
      const x = (Math.random() - 0.5) * 2;
      const z = (Math.random() - 0.5) * 2;

      triangles.push({
        normal: [0, 0, 1],
        vertices: [
          [x, 0, z],
          [x + 0.1, 0.5, z],
          [x - 0.1, 0.5, z],
        ],
      });
    }
  } else {
    // Default cube
    const vertices = [
      [-1, -1, -1],
      [1, -1, -1],
      [1, 1, -1],
      [-1, 1, -1],
      [-1, -1, 1],
      [1, -1, 1],
      [1, 1, 1],
      [-1, 1, 1],
    ];

    const faces = [
      [0, 1, 2],
      [0, 2, 3],
      [4, 6, 5],
      [4, 7, 6],
      [0, 4, 5],
      [0, 5, 1],
      [2, 6, 7],
      [2, 7, 3],
      [0, 3, 7],
      [0, 7, 4],
      [1, 5, 6],
      [1, 6, 2],
    ];

    faces.forEach((face) => {
      triangles.push({
        normal: [0, 0, 0],
        vertices: [
          vertices[face[0]] as [number, number, number],
          vertices[face[1]] as [number, number, number],
          vertices[face[2]] as [number, number, number],
        ],
      });
    });
  }

  // Build STL file
  const triangleCount = triangles.length;
  const totalSize = 80 + 4 + triangleCount * 50;
  const buffer = new ArrayBuffer(totalSize);
  const view = new DataView(buffer);

  // Write header (already done)
  // Write triangle count
  view.setUint32(80, triangleCount, true);

  // Write triangles
  let offset = 84;
  triangles.forEach((tri) => {
    // Normal
    view.setFloat32(offset, tri.normal[0], true);
    offset += 4;
    view.setFloat32(offset, tri.normal[1], true);
    offset += 4;
    view.setFloat32(offset, tri.normal[2], true);
    offset += 4;

    // Vertices
    tri.vertices.forEach((v) => {
      view.setFloat32(offset, v[0], true);
      offset += 4;
      view.setFloat32(offset, v[1], true);
      offset += 4;
      view.setFloat32(offset, v[2], true);
      offset += 4;
    });

    // Attribute byte count
    view.setUint16(offset, 0, true);
    offset += 2;
  });

  return buffer;
}

/**
 * Download STL file
 */
export function downloadSTL(
  organism: string,
  designName: string
): void {
  const stlBuffer = generateSTLModel(organism, designName);
  const blob = new Blob([stlBuffer], { type: "application/octet-stream" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `${organism}-${designName}-${Date.now()}.stl`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Generate a shareable link with solution details
 */
export function generateShareLink(
  challenge: string,
  solutionId: string
): string {
  const params = new URLSearchParams({
    challenge: challenge,
    solution: solutionId,
    timestamp: Date.now().toString(),
  });

  return `${window.location.origin}/solution?${params.toString()}`;
}
